# Generated by Django 2.2.6 on 2019-10-20 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memoapp', '0002_auto_20191017_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='When you hit it on...'),
        ),
        migrations.AlterField(
            model_name='day',
            name='text',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='day',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Want ...'),
        ),
    ]
