# Generated by Django 2.2.6 on 2019-10-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoapp', '0004_auto_20191022_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='title',
            field=models.CharField(max_length=200, verbose_name="What's on your mind?"),
        ),
    ]
